# Chip: AABB Contains Point
# Ports:
#   Input 1 | Type: vector | Name: AABB Min
#   Input 2 | Type: vector | Name: AABB Max
#   Input 3 | Type: vector | Name: Point
#   Output 1 | Type: bool | Name: Contains Point

# Required Libraries
#   - None

variables:
    _CHIP_VER = 1.0.0
    _CURRENT_EXEC = None

function CHIP_AABB_CONTAINS_POINT_TRIGGER(input1 : vector, input2 : vector, input3 : vector):
    return "{error.not_implemented}"
