# Chip: API Request
# Ports:
#   Input 1 | Type: exec | Name: Trigger
#   Input 2 | Type: api | Name: API
#   Output 1 | Type: exec | Name: Run
#   Output 2 | Type: exec | Name: On Response
#   Output 3 | Type: bool | Name: Success
#   Output 4 | Type: int | Name: Response Code
#   Output 5 | Type: any | Name: Data

# Required Libraries
#   - None

variables:
    _CHIP_VER = 1.0.0
    _CURRENT_EXEC = None

function CHIP_API_REQUEST_TRIGGER(input2 : object):
    return "{error.not_implemented}"
