# ===================== #
# Chip: API Request
# Last Modified: 2026 05 03 21:17
# Created: 2026 05 03 21:17
# ===================== #

# ===================== #
# Circuit Data
# ===================== #
# Inputs
# 1 (Trigger) (static) [ exec ] (min n/a, max n/a)
# 2 (API) (static) [ api ] (min n/a, max n/a)
# -------------------- #
# Outputs
# 1 (Run) (static) [ exec ] (min n/a, max n/a)
# 2 (On Response) (static) [ exec ] (min n/a, max n/a)
# 3 (Success) (static) [ bool ] (min n/a, max n/a)
# 4 (Response Code) (static) [ int ] (min n/a, max n/a)
# 5 (Data) (static) [ any ] (min n/a, max n/a)
# =====================


variables:
    version = "1.0.0"

execution = "port1"

function CHIP_api_request(port2: object):
    return 'TRIGGER.ERROR.NOT_IMPLEMENTED'
