# Chip: List Insert
# Ports:
#   Input 1 | Type: list<any> | Name: List
#   Input 2 | Type: int | Name: Index
#   Input 3 | Type: any | Name: Value
#   Output 1 | Type: list<any> | Name: List

# Required Libraries
#   - None

variables:
    _CHIP_VER = 1.0.0
    _CURRENT_EXEC = None

function CHIP_LIST_INSERT_TRIGGER(input1 : object, input2 : int, input3 : object):
    return "{error.not_implemented}"
