# ===================== #
# Chip: Acos
# Last Modified: 2026 04 16 ACDT
# Loaded: 2026 04 16 23:18 ACDT
# ===================== #

# ===================== #
# Circuit Data
# ===================== #
# Inputs
# port1 (Input) [static]: float
# -------------------- #
# Outputs
# output1 (Result) [static]: float
# ===================== #

function port1(port1: object):
    if port1 < -1:
        return acos(-1)
    if port1 > 1:
        return acos(1)
    return acos(port1)
