# ===================== #
# Chip: Get Authority
# Last Modified: 2026 05 03 21:17
# Created: 2026 05 03 21:17
# ===================== #

# ===================== #
# Circuit Data
# ===================== #
# Inputs
# None
# -------------------- #
# Outputs
# 1 (Authority) (static) [ player ] (min n/a, max n/a)
# =====================


variables:
    version = "1.0.0"

execution = "port1"

function CHIP_get_authority():
    return 'TRIGGER.ERROR.NOT_IMPLEMENTED'
