# ===================== #
# Chip: Instance Get Is Private
# Last Modified: 2026 05 03 21:17
# Created: 2026 05 03 21:17
# ===================== #

# ===================== #
# Circuit Data
# ===================== #
# Inputs
# None
# -------------------- #
# Outputs
# 1 (Is Private) (static) [ bool ] (min n/a, max n/a)
# =====================


variables:
    version = "1.0.0"

execution = "port1"

function CHIP_instance_get_is_private():
    return 'TRIGGER.ERROR.NOT_IMPLEMENTED'
