# Chip: Execution Integer Switch
# Ports:
#   Input 1 | Type: exec | Name: Exec
#   Input 2 | Type: int | Name: Value
#   Output 1 | Type: exec | Name: Failed
#   Output 2 | Type: execc | Name: {dynamic_port_index}

# Required Libraries
#   - None

variables:
    _CHIP_VER = 1.0.0
    _CURRENT_EXEC = None

function CHIP_EXECUTION_INTEGER_SWITCH_TRIGGER(input2 : int):
    return "{error.not_implemented}"
