# Chip: For
# Ports:
#   Input 1 | Type: exec | Name: 
#   Input 2 | Type: int | Name: From (Inclusive)
#   Input 3 | Type: int | Name: To (Exclusive)
#   Output 1 | Type: exec | Name: Loop
#   Output 2 | Type: int | Name: Index
#   Output 3 | Type: exec | Name: Done

# Required Libraries
#   - None

variables:
    _CHIP_VER = 1.0.0
    _CURRENT_EXEC = None

function CHIP_FOR_TRIGGER(input2 : int, input3 : int):
    return "{error.not_implemented}"
