# Chip: For Each
# Ports:
#   Input 1 | Type: exec | Name: 
#   Input 2 | Type: list<any> | Name: List
#   Output 1 | Type: exec | Name: Loop
#   Output 2 | Type: any | Name: Item
#   Output 3 | Type: int | Name: Index
#   Output 4 | Type: exec | Name: Done

# Required Libraries
#   - None

variables:
    _CHIP_VER = 1.0.0
    _CURRENT_EXEC = None

function CHIP_FOR_EACH_TRIGGER(input2 : object):
    return "{error.not_implemented}"
