# ===================== #
# Chip: If Player Is Valid And Local
# Last Modified: 2026 05 03 21:17
# Created: 2026 05 03 21:17
# ===================== #

# ===================== #
# Circuit Data
# ===================== #
# Inputs
# 1 () (static) [ exec ] (min n/a, max n/a)
# 2 (Player) (static) [ player ] (min n/a, max n/a)
# -------------------- #
# Outputs
# 1 (Is Valid And Local) (static) [ exec ] (min n/a, max n/a)
# 2 (Is Not Valid Or Not Local) (static) [ exec ] (min n/a, max n/a)
# =====================


variables:
    version = "1.0.0"

execution = "port1"

function CHIP_if_player_is_valid_and_local(port2: object):
    return 'TRIGGER.ERROR.NOT_IMPLEMENTED'
