# Chip: If Player Is Valid And Local
# Ports:
#   Input 1 | Type: exec | Name: 
#   Input 2 | Type: player | Name: Player
#   Output 1 | Type: exec | Name: Is Valid And Local
#   Output 2 | Type: exec | Name: Is Not Valid Or Not Local

# Required Libraries
#   - None

variables:
    _CHIP_VER = 1.0.0
    _CURRENT_EXEC = None

function CHIP_IF_PLAYER_IS_VALID_AND_LOCAL_TRIGGER(input2 : object):
    return "{error.not_implemented}"
