# Chip: If Player Is Local
# Ports:
#   Input 1 | Type: exec | Name: 
#   Input 2 | Type: player | Name: Player
#   Output 1 | Type: exec | Name: Is Local Player
#   Output 2 | Type: exec | Name: Is Not Local Player

# Required Libraries
#   - None

variables:
    _CHIP_VER = 1.0.0
    _CURRENT_EXEC = None

function CHIP_IF_PLAYER_IS_LOCAL_TRIGGER(input2 : object):
    return "{error.not_implemented}"
