# ===================== #
# Chip: Vector3 Dot
# Last Modified: 2026 04 16 ACDT
# Loaded: 2026 04 16 23:08 ACDT
# ===================== #

# ===================== #
# Circuit Data
# ===================== #
# Inputs
# port1 (LHS) [static]: vector
# port2 (RHS) [static]: vector
# -------------------- #
# Outputs
# output1 (Result) [static]: float
# ===================== #

function port1(port1: object, port2: object):
    return 0
