# ===================== #
# Chip: Vector3 Split
# Last Modified: 2026 04 16 ACDT
# Loaded: 2026 04 16 23:08 ACDT
# ===================== #

# ===================== #
# Circuit Data
# ===================== #
# Inputs
# port1 (Vector3) [static]: vector
# -------------------- #
# Outputs
# output1 (X) [static]: float
# output2 (Y) [static]: float
# output3 (Z) [static]: float
# ===================== #

function port1(port1: object):
    return 0
