# ===================== #
# Chip: And
# Last Modified: 2026 04 16 ACDT
# Loaded: 2026 04 16 23:08 ACDT
# ===================== #

# ===================== #
# Circuit Data
# ===================== #
# Inputs
# port1 (Input) [dynamic]: bool (min 2, max unbounded)
# -------------------- #
# Outputs
# output1 (Result) [static]: bool
# ===================== #

function port1(port1: object):
    return false
