# ===================== #
# Chip: Not
# Last Modified: 2026 05 03 21:17
# Created: 2026 05 03 21:17
# ===================== #

# ===================== #
# Circuit Data
# ===================== #
# Inputs
# 1 (Input) (static) [ bool ] (min n/a, max n/a)
# -------------------- #
# Outputs
# 1 (Result) (static) [ bool ] (min n/a, max n/a)
# =====================


variables:
    version = "1.0.0"

execution = "port1"

function CHIP_not(port1: object):
    return 'TRIGGER.ERROR.NOT_IMPLEMENTED'
