# ===================== #
# Chip: Greater Than
# Last Modified: 2026 04 16 ACDT
# Loaded: 2026 04 16 23:04 ACDT
# ===================== #

# ===================== #
# Circuit Data
# ===================== #
# Inputs
# port1 (Input) [dynamic]: float | int | vector (min 2, max unbounded)
# -------------------- #
# Outputs
# output1 (Result) [static]: bool
# ===================== #

function port1(port1: object):
    return false
