# ===================== #
# Chip: Min
# Last Modified: 2026 04 16 ACDT
# Loaded: 2026 04 16 23:08 ACDT
# ===================== #

# ===================== #
# Circuit Data
# ===================== #
# Inputs
# port1 (Value) [dynamic]: float | int (min 2, max unbounded)
# -------------------- #
# Outputs
# output1 (Result) [static]: float | int
# ===================== #

function port1(port1: object):
    return 0
